version: "3"
services:
  redis:
    image: redis

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  vote:
    image: voting-app
    ports:
      - 2000:80

  worker:
    image: worker-app

  result:
    image: result-app
    ports:
      - 2001:80
